### ISSUE TITLE
Merge two files

### ISSUE THREAD

**Issue by ChristianKniep** [ahmet2mir/wildq#10]
I'd like to join two yaml files and I am struggling to find the right command. 

Example
```bash
~ # cat k1.yaml 
base:
  key1: val1
~ # cat k2.yaml 
base:
  key2: val2
```

I'd like to merge the two with the result being...

```yaml
base:
  key1: val1
  key2: val2
```
