### ISSUE TITLE
Add key/value item to YAML

### ISSUE THREAD

**Issue by kniec** [ahmet2mir/wildq#7]
Hi Ahmet,

thanks for the tool - I am working on more workshops like the once you already linked in your ReadMe. :) 
And I need to change some YAML - wondering whether you can help me out.

### Wildq Version
```bash
$ wildq --version
wildq, version 1.1.10
```

### Affected FileType(s)
Please list the filetypes as a list, for example:
- yaml

## Challenge

I have a structure like that:

```yaml
Key1: Value1
Items:
- Name: item1
  Type: host
  Tags:
   - tag1: val1
   - tag2: val2
- Name: item2
  Type: host
  Tags:
   - tag1: val1
   - tag2: val2
```

I am struggling to  add `Items` using `wildq`. Any hints?

Cheers
Christian

**Comment by kniec** [comment]
It it would be a simple string as an item, I figured:
```
cat test.yaml \
      |wildq -i yaml -M '.Items.Args[0] = "a"' \
      |sponge test.yaml
```

**Comment by ahmet2mir** [comment]
Hello Christian,

Very useful workshop, I discovered `sponge` command and nice tips on wildq :)

As `wildq` rely on `jq` lib, everything you found on jq should be used in wildq.

For example, with jq you could simply [merge 2 arrays](https://stackoverflow.com/a/42248841) with `+=` followed by another array.

```bash
wildq -i yaml -M \
  '.Items += [{"Name":"item3","Type": "host", "Tags":[{"tag1":"val1"},{"tag2":"val2"}]}]' \
  test.yaml
```

Give

```yaml
Items:
  - Name: item1
    Tags:
      - tag1: val1
      - tag2: val2
    Type: host
  - Name: item2
    Tags:
      - tag1: val1
      - tag2: val2
    Type: host
  - Name: item3
    Tags:
      - tag1: val1
      - tag2: val2
    Type: host
Key1: Value1
```
